# Generated by Django 6.0.1 on 2026-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='task',
            name='effort',
        ),
        migrations.AddField(
            model_name='subtask',
            name='story_points',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (7, '7')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (8, '8'), (13, '13'), (21, '21')], default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('do', '1) Urgente e Importante (Hacer)'), ('plan', '2) Importante no Urgente (Planificar)'), ('delegate', '3) Urgente no Importante (Delegar)'), ('eliminate', '4) Ni Urgente ni Importante (Eliminar)')], default='plan', max_length=15),
        ),
    ]
