# Generated by Django 6.0.1 on 2026-01-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subtask_effort_remove_task_effort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('do', '1) Urgente e Importante '), ('plan', '2) Importante no Urgente '), ('delegate', '3) Urgente no Importante '), ('eliminate', '4) Ni Urgente ni Importante')], default='plan', max_length=15),
        ),
    ]
