# Generated by Django 6.0.1 on 2026-01-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_priority_taskstatuslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatuslog',
            old_name='note',
            new_name='comment',
        ),
    ]
