# Generated by Django 6.0.1 on 2026-01-28 01:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_note_taskstatuslog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spent_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
