# Generated by Django 6.0.1 on 2026-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_spent_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_admin_users', models.PositiveIntegerField(default=5)),
                ('max_normal_users', models.PositiveIntegerField(default=10)),
                ('max_projects', models.PositiveIntegerField(default=5)),
                ('max_tasks', models.PositiveIntegerField(default=50)),
                ('max_files', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Plan (Límites)',
                'verbose_name_plural': 'Plan (Límites)',
            },
        ),
    ]
