# Generated by Django 6.0.1 on 2026-01-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planlimits'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kpis',
            field=models.TextField(blank=True, verbose_name='KPIs'),
        ),
    ]
