# Generated by Django 6.0.1 on 2026-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_kpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.PositiveSmallIntegerField(default=5)),
                ('end_hour', models.PositiveSmallIntegerField(default=9)),
            ],
            options={
                'verbose_name': 'Configuración Daily',
                'verbose_name_plural': 'Configuración Daily',
            },
        ),
    ]
