# Generated by Django 6.0.2 on 2026-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_subtask_attachment_subtaskattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('do', 'Urgente e Importante'), ('plan', 'Importante no Urgente'), ('delegate', 'Urgente no Importante'), ('eliminate', 'Ni Urgente ni Importante')], default='plan', max_length=15),
        ),
    ]
